#!/bin/zsh
# This files contains git aliases

alias g='git'

alias gs='git status'
alias gf='git fetch'
alias gp='git pull'
alias gc='git commit'

alias gd='git diff'

# worktree
alias gw='git wortktree'
alias gwl='git worktree list'

# TODO: add comment and alias to add (remote) branch as new worktree (while branching)
# git worktree add --track -b <branch-name> <dir-name> <remote>/<base-branch-name>
# TODO: add comment and alias to clone repository with greater worktree support

