#!/bin/zsh
# This files contains my general aliases for zsh

# reload zsh configuration
alias reload='exec zsh'

# easier directory handling
alias ~='cd ~'

ddot='..'
ddotPath='..'

for i ({1..9})
do
  alias "$ddot"="cd $ddotPath"
  alias "..$i"="cd $ddotPath"

  ddot="$ddot."
  ddotPath="$ddotPath/.."
done

unset ddot ddotPath i

