[font]
size = 10

[font.normal]
family = "fira code nerd font"
style = "Regular"

[font.bold]
family = "fira code nerd font"
style = "bold"

[font.italic]
family = "fira code nerd font"
style = "Italic"

[font.bold_italic]
family = "fira code nerd font"
style = "Bold Italic"

